application: deirhhsendmail
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: sendmail.php

